name: Build Eleven OS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Eleven ISO
        uses: anton-sh6/arch-build-action@v2
        with:
          iso_name: Eleven-OS-v1
